hoangnm/react-native-week-view

src/Header/Header.styles.js
juillet 2019 doesn't fit with the others.
=> fix title top border to fit in

example/App.js, example/package.json, example/yarn.lock, package.json, src/Events/Events.js, src/Events/Events.styles.js, src/Header/Header.js, src/Times/Times.js, src/Times/Times.styles.js, src/WeekView/WeekView.js, src/WeekView/WeekView.styles.js, src/utils.js, yarn.lock
* Move events sorting to `WeekView`, to only sort them once
- An `eventsByDate` object is created, with date as keys (in format "YYYY-MM-DD") and list of events as values
- Then each `Events` component accesses the events from the same object, avoiding extra copies and sorting more than necessary
- The sorting is performed over the list of events from the same day, which should be much less than the number of total events
* Memoize functions in `WeekView.render`, to avoid re-calculations when not necessary
* Make `Events` and `Header` `PureComponents`, to avoid extra re-renders
* Create `Times` component to display time column (is a `PureComponent` to avoid extra re-renders)
* In `WeekView.scrollEnded` only update the state if the date actually changes, to avoid an extra re-render
* Other …
=> Improve performance of events processing

README.md, example/App.js, src/Event/Event.js, src/Events/Events.js, src/Events/Events.styles.js, src/Header/Header.js, src/Times/Times.js, src/Title/Title.js, src/WeekView/WeekView.js
Multiple fixes:
* Add `date` argument to `onGridClick()` callback. Fixes #47 
* In `Title`, avoid displaying an empty `<Text>` if `showTitle` is false. The `<View>` is still displayed to show background color.
* Add `hourTextStyle`, `headerTextStyle`, `eventContainerStyle` props. Fixes #35 and fixes #45 
(PS: sorry if these are too many changes in the same PR)
=> Pass more styles prop and misc fixes

src/utils.js
Fixes #55
Now, when `numberOfDays === 7`, the week always starts in a monday, independent of the `selectedDate` passed
=> Fix isoweekday issue

README.md, example/App.js, src/WeekView/WeekView.js
Add method to navigate to a specific date, fixes #54  
Notes:
* This is a breaking change (to move to a date). Maybe we could create a changelog documenting this?
* There is a slight hack with the `setTimeout(..., 0)` method. This is needed so the child `VirtualizedList` gets updated first, and only then the `this.eventsGrid.scrollToIndex()` gets called.
- If the `this.eventsGrid.scrollToIndex()` function is called first, the new pages are not rendered yet
- I could not make it work with other callback managers, such as `InteractionsManager.runAfterInteractions`
* The code got a little messy, if you have any suggestions to improve it let me know!
=> Add goToDate() method

src/Header/Header.js, src/Title/Title.js
Fixes #64 
This is a (small) breaking change, as the text color should not be set in the `headerStyle` prop, but only in the `headerTextStyle` prop. (Only users setting the text-color via `headerStyle.color` would be affected)
=> Don't use headerStyle.color

src/Events/Events.js
Fixes #59 
Notes:
* The behavior when 2 events are overlapped is pretty much the same than it was before
* When 3 or more events are overlapped, the amount of vertical "lanes" is computed, i.e. how many events will be side to side
=> Optimize horizontal space when 3+ events are overlapped

src/WeekView/WeekView.js, src/utils.js
Fixes #76 
* Now the `initialDates` array contains the correct initial dates from each page,  which did not occur before if `numberOfDays` was 7
* Now the "decision" to start a week on Mondays gets relegated to the `calculatePagesDates()` method, and `calculateDaysArray` is simplified
=> Fix initialDates shift bug

README.md, docs/CHANGELOG.md, example/App.js, src/Events/Events.js, src/Events/Events.styles.js, src/NowLine/NowLine.js, src/NowLine/NowLine.styles.js, src/WeekView/WeekView.js, src/utils.js
Fixes #73 
Adds a now-line, which is a red line with a circle to the left, indicating the time right now (see screenshots in the issue).
* Adds two props: `showNowLine` and `nowLineColor`
* The line gets updated every minute, with a `setInterval` function
* Needs to be merged after #77 (needs that bug fix to work)
=> Feature: add now-line

README.md, src/WeekView/WeekView.js
Fixes #119 
Add prop `weekStartsOn` to set initial day of the week (e.g. sunday, monday or any other day)
=> Add weekStartsOn prop

src/WeekView/WeekView.js
Fixes #109
* react-native bug affecting 0.64.0, `VirtualizedList` calls `onMomentumScrollEnd` more than once sometimes
* This PR is a workaround, the callback gets called only once
=> Fix onMomentumScrollEnd called twice

README.md, src/Header/Header.js, src/WeekView/WeekView.js
Fixes #104
Add `TodayHeaderComponent` prop, to allow highlighting today in the header.
I was not sure on how to visually highlight today in the header, so with this prop the developer can fully customize how it looks. Examples: bold the font, add a rounded box, change the background color, etc.
=> Feature: add TodayHeaderComponent

README.md, src/Events/Events.js, src/WeekView/WeekView.js
* Added `onGridLongPress` prop, to allow different user-interactions with the grid
* I realize the name is different than `onGridClick` (click vs press). I think in mobile "press" sounds more natural. We could rename `onGridClick` to `onGridPress` in a future (breaking) version
=> Feature: add onGridLongPress prop

src/Events/Events.js, src/NowLine/NowLine.js
Fixes #131 
When `hoursInDisplay` change on the fly, the events' style (position) must be recalculated, and the `NowLine` must be repositioned
* The main change in `Events.js`: the `processEvents()` method is now also memoized by `hoursInDisplay`
* I refactored some methods into functions --> so it is more clear on which props do they depend, when they use `this.props` or `this.state`, etc --> to avoid bugs like this one (regarding memoization)
* The change in `NowLine.js`: the line is updated in `componentDidUpdate`
=> Bug: events break when changing hoursInDisplay

README.md, package.json
update supported react and react-native versions.
=> update supported react and react-native version

README.md, example/App.js, src/Events/Events.js
Fixes #148
* The `startHour` argument is redundant now (i.e. `=== date.getHours()`), I'd say we can remove it in a future 1.x release? (would be a breaking change)
=> Add precision up to seconds in onGrid callbacks

README.md, example/App.js, src/Events/Events.js, src/Events/Events.styles.js, src/WeekView/WeekView.js
Fixes #43, fixes #138, fixes #156
* Add `gridRowStyle` and `gridColumnStyle` props, to modify grid horizontal and vertical lines (separated). Usage:
```js
gridRowStyle={{ borderTopWidth: <width>, borderColor: <color> }} // horizontal lines width and color
gridColumnStyle={{ borderLeftWidth: <width>, borderColor: <color> }} // vertical lines width and color
```
* I removed an extra `<View/>` element, for simplicity
I'm not sure the props I chose are the best option, lmk if you think there are better options
=> Add gridRowStyle and gridColumnStyle props

.github/workflows/codeql-analysis.yml
Unused languages (tests were failing)
=> Remove java and ruby from codeql

README.md, src/WeekView/WeekView.js
Seems easier to understand, there are a lot of props
=> Chore: Display props in README as table

src/Events/Events.js, src/Events/Events.styles.js, src/Times/Times.js, src/Times/Times.styles.js, src/Title/Title.js, src/Title/Title.styles.js, src/WeekView/WeekView.js, src/WeekView/WeekView.styles.js, src/utils.js
Main changes:
* Remove hard-coded `CONTAINER_WIDTH` variable
* Calculate dynamically `dimensions = { dayWidth, pageWidth, timeLabelsWidth }` to define the widths of the views
This refactor will allow solving later:
* issues #128, #185, and #186 **(already solved in upcoming PRs)**
* responsiveness (#38, #142) **(in the future)**
=> Refactor: compute WeekView width dinamically

README.md, example/App.js, src/Events/Events.js, src/NowLine/NowLine.js, src/WeekView/WeekView.js, src/utils.js
=> Add onTimeScrolled callback

.gitignore, docs/DEVELOPING.md, example/App.js, example/android/app/build.gradle, example/android/app/proguard-rules.pro, example/package.json, src/Events/Events.js, src/WeekView/WeekView.js
Performance improvements, part of https://github.com/hoangnm/react-native-week-view/discussions/209
* Enable profiling with android systrace (see DEVELOPING.md)
* Optimize some FlatList props (following [react-native recommendations](https://reactnative.dev/docs/optimizing-flatlist-configuration#props))
* --> Improves performance of scrolling horizontally
* Preserve reference to each event instead of spreading (could allow memoizing or using a PureComponent in the future)
=> Improve performance by FlatList props and preserving Event ref

.github/workflows/codeql-analysis.yml, .github/workflows/linter.yml, .github/workflows/tests.yml
Badges should be passing:
See https://github.com/hoangnm/react-native-week-view/actions/workflows/linter.yml/badge.svg, https://github.com/hoangnm/react-native-week-view/actions/workflows/tests.yml/badge.svg, should be passing
This PR _should_ fix that.
=> Fix github actions badge

.eslintrc, example/package.json, index.d.ts, package.json, yarn.lock
* Enable linting TS files
* Add missing fields to WeekViewEvent type declaration
=> Chore: TS + ESlint

index.d.ts
headerTextStyle has the wrong type `StyleProp<ViewStyle>` when it is passed to a `<Text>` element
=> Bug: Incorrect headerTextStyle type

example/App.js, package.json, src/WeekView/WeekView.js, src/__tests__/WeekView/horizontalSwipe.test.js, src/__tests__/expect.js, src/__tests__/setup.js, src/utils/pages.js
* Add a test for horizontal swiping
* having this test should be useful for fixing #259 and improving overall performance
* has limitations (see comments)
* Fix small bug when `prependMostRecent: true` (onSwipeNext and onSwipePrev calls were swapped)
* Refactor code into `utils/pages.js`
=> Chore: add minimal horizontal-scroll test

src/Event/Event.js, src/Events/Events.js
A weird bug occurs only when `runOnJS=true`:
=> Fix weird UI bug
