src/Header/Header.js, src/WeekView/WeekView.js, src/utils.js
I have implemented a little change to be able to select lang to display dates with selected language.
For example lang='es' will display in header 'Lun, Mar, Mie, Jue, Vie, Sab, Dom'
=> Language selector

README.md, example/App.js, index.js, src/utils.js
Has function to add customized locale instead of using pre-defined locales from momentjs to avoid loading unnecessary locales.
=> Has function to customize locale

src/Events/Events.js, src/Header/Header.js, src/WeekView/WeekView.js
- removed componentWillReceiveProps
- added ability to show 5 days
=> removed componentWillReceiveProps

README.md, example/App.js, src/Event/Event.js, src/Events/Events.js, src/Events/Events.styles.js, src/WeekView/WeekView.js, src/WeekView/WeekView.styles.js, src/utils.js
* Add `hoursInDisplay` prop to select amount of hours shown in the screen
* Add `startHour` prop to set the initial hour to display
* Disable event-pressing if no handler (`onEventPress`) is passed
* Fix typo in README.md
=> Improve vertical behavior

src/Events/Events.js
Fixes #17, more than 2 events overlapping
=> Fixes more than 2 events overlapping

.gitignore, README.md, src/Event/Event.js, src/Event/Event.styles.js, src/Events/Events.js, src/Events/Events.styles.js, src/Header/Header.js, src/Title/Title.js, src/WeekView/WeekView.js, src/WeekView/WeekView.styles.js, src/utils.js
Add a prop to provide a custom component to render inside events. I added an usage example in the README.
Also, minor changes to reuse variables
=> Feature: custom event component

README.md, src/Events/Events.js, src/Header/Header.js, src/WeekView/WeekView.js, src/utils.js
* Implement right-to-left feature, with the `rightToLeft` prop. Fixes #49 
* Add `prependMostRecent` prop, to be able to choose to which side to flicker when scrolling. See #39
=> Feature: RTL

src/Events/Events.js
Add a constant to allow overlapping, as discussed in #50
=> Allow events to overlap by 2 seconds

README.md, src/WeekView/WeekView.js
Fixes #96 
* Add `goToNextPage()` and `goToPrevPage()` methods, to allow moving pages programatically
* Needs to be merged after #97 (this branch includes that fix on `goToDate()`)
=> Add goToNextPage method

README.md, example/App.js, src/Events/Events.js, src/Times/Times.js, src/WeekView/WeekView.js, src/utils.js
Fixes #91 
I added the prop `timeStep`, to indicate the step in the time labels
=> Add timeStep prop

package.json, src/Events/Events.js, src/NowLine/NowLine.js, src/WeekView/WeekView.js, src/utils.js
Fixed some linter issues from the last PRs (I only catched them after merging #84)
Now `npm run lint/test` should run with success in the main folder and `example/`
=> Fix linter issues

README.md, src/Event/Event.js, src/Events/Events.js, src/WeekView/WeekView.js
Add `onEventLongPress` prop, to allow more user interactions with the events
=> Feature: add onEventLongPress prop

example/.gitignore, example/package.json
* Add a couple of files to `yarn sync` script
* Add package-lock to gitignore (we should use only yarn, not npm)
=> Improve sync yarn script

src/Event/Event.js
=> Fix drag drop memoized bug

package.json
Add support for next major react version (v17) as requested here: https://github.com/hoangnm/react-native-week-view/pull/144#issuecomment-1068301500
=> Add support for react 17

README.md, src/Header/Header.js, src/WeekView/WeekView.js
Closes #134, to use a custom component for the day in the header
=> Add DayHeaderComponent prop

README.md, example/App.js, src/Events/Events.js, src/NowLine/NowLine.js, src/WeekView/WeekView.js
Fixes #177, fixes #168 and fixes #70
=> Add beginAgendaAt and endAgendaAt props

.github/workflows/linter.yml
Follow up to #222, linter badge still failing:
https://github.com/hoangnm/react-native-week-view/actions/workflows/linter.yml/badge.svg
=> Avoid name collisions in linter.yml

.gitignore, package.json, src/Event/Event.js, src/Event/Event.styles.js, src/Events/Events.js, src/WeekView/WeekView.js, src/__tests__/Event.test.js, src/__tests__/WeekView.test.js, yarn.lock
Add tests for displaying, pressing and dragging events. I tried writing the tests to resemble user behavior as much as possible
=> Add tests: display, press and drag events

src/WeekView/WeekView.js
=> Refactor: build new pages immutably (avoid inplace operations)

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Remove possible culprits (labels, and strings `<<`, `>>`)
=> Fix issue templates by cleaning markdown

index.js, src/Events/Events.js, src/Events/Events.styles.js, src/Header/Header.js, src/Header/Header.styles.js, src/NowLine/NowLine.js, src/Times/Times.js, src/Times/Times.styles.js, src/Title/Title.js, src/WeekView/WeekView.js, src/WeekView/WeekView.styles.js, src/__tests__/utils.test.js, src/utils.js, src/utils/dates.js, src/utils/dimensions.js, src/utils/gestures.js
* When `hoursInDisplay` changes, the UI updates smoothly (before it jumped, or did not update at all)
* Responsive to orientation changes
https://user-images.githubusercontent.com/20805451/177889593-dfed2c39-9fbd-48ea-9da6-07c53afa37e7.mp4
This is needed for the coming pinch-vertical feature (#130)
=> Refactor: height responsiveness

docs/DEVELOPING.md, src/WeekView/WeekView.js
props disableVirtualization, removeClippedSubview 
hotfix for #259
=> Expose VirtualizedList props

src/__tests__/pipeline/overlap.example.js, src/__tests__/pipeline/overlap.test.js, src/pipeline/overlap.js
=> Fix overlap-ignore bug

.github/ISSUE_TEMPLATE/bug_report.md
Require users to specify  gesture-handler and reanimated versions
=> Update github bug template

webdocs/docusaurus.config.js, webdocs/package.json, webdocs/yarn.lock
Note: searchbar is only useful in production: `cd webdocs/ && yarn build && yarn serve`
=> Add searchbar to docs

index.d.ts
=> Add missing props to index.ts
